import {test} from 'node:test';import assert from 'node:assert/strict';import {soundEvents} from '../dist/audio.js';
const state=(actor=1,extras={})=>({room:'r',hand:1,street:'preflop',actor,seat:0,paused:false,actionCount:1,...extras});
test('turn alert fires on transition, not on repeated polling',()=>{const a=state(1),b=state(0,{actionCount:2});assert.ok(soundEvents(a,b).includes('turn'));assert.deepEqual(soundEvents(b,b),[]);assert.ok(!soundEvents(b,state(1,{actionCount:3})).includes('turn'));});
test('new hand, pause, completed hand and opponent seat cannot trigger a false turn alert',()=>{assert.ok(soundEvents(state(0),state(0,{hand:2})).includes('turn'));assert.ok(!soundEvents(state(1),state(0,{paused:true})).includes('turn'));assert.ok(!soundEvents(state(1),state(null,{street:'complete'})).includes('turn'));assert.ok(soundEvents(state(0,{paused:true}),state(0)).includes('turn'));});
test('audio starts only after enabling it, music is independent, and mute silences cues',async()=>{
 const previous={document:globalThis.document,window:globalThis.window,localStorage:globalThis.localStorage};const nodes=new Map();let created=0,started=0;const buses=[];
 const control=id=>{if(!nodes.has(id))nodes.set(id,{value:30,addEventListener(t,f){this[t]=f;},setAttribute(){}});return nodes.get(id);};
 class Audio {constructor(){created++;this.state='running';this.currentTime=0;this.destination={};}async resume(){}createGain(){const node={gain:{value:0,setValueAtTime(v){this.value=v;},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};buses.push(node);return node;}createOscillator(){return {frequency:{},connect(){},disconnect(){},start(){started++;},stop(){}};}async close(){}}
 globalThis.document={hidden:false,addEventListener(){}};globalThis.window={AudioContext:Audio,addEventListener(){}};globalThis.localStorage={getItem:()=>null,setItem(){}};
 try{const {mountAudio}=await import('../dist/audio.js'),audio=mountAudio({innerHTML:'',querySelector:control});audio.update(state(0));assert.equal(created,0);await control('[data-sound]').click();assert.equal(created,1);assert.ok(started>=2);assert.equal(control('[data-music]').textContent,'Music off');const after=started;audio.update(state(0));assert.equal(started,after);await control('[data-sound]').click();assert.equal(buses[1].gain.value,0);audio.update(state(1));audio.update(state(0));assert.equal(started,after);
 }finally{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
});
test('music control initializes the room effects and percussion, and can stop independently',async()=>{
 const old={document:globalThis.document,window:globalThis.window,localStorage:globalThis.localStorage};const controls=new Map();let starts=0;
 const param=()=>({value:0,setValueAtTime(v){this.value=v;},exponentialRampToValueAtTime(){}}),node=()=>({gain:param(),frequency:param(),Q:param(),delayTime:param(),connect(){},disconnect(){},start(){starts++;},stop(){}});
 class Audio {constructor(){this.state='running';this.currentTime=0;this.sampleRate=8000;this.destination={};}async resume(){}createGain(){return node();}createOscillator(){return node();}createBiquadFilter(){return node();}createDelay(){return node();}createBufferSource(){return node();}createBuffer(c,length){return {getChannelData:()=>new Float32Array(length)};}async close(){}}
 globalThis.document={hidden:false,addEventListener(){}};globalThis.window={AudioContext:Audio,addEventListener(){}};globalThis.localStorage={getItem:()=>null,setItem(){}};
 const get=s=>{if(!controls.has(s))controls.set(s,{addEventListener(t,f){this[t]=f;},setAttribute(){}});return controls.get(s);};
 try{const {mountAudio}=await import('../dist/audio.js');mountAudio({innerHTML:'',querySelector:get});await get('[data-music]').click();assert.ok(starts>10);assert.equal(get('[data-music]').textContent,'Music on');assert.equal(get('[data-sound]').textContent,'Sound off');await get('[data-music]').click();assert.equal(get('[data-music]').textContent,'Music off');}finally{if(get('[data-music]').textContent==='Music on')await get('[data-music]').click();for(const [k,v] of Object.entries(old)){if(v===undefined)delete globalThis[k];else globalThis[k]=v;}}
});
